### ISSUE TITLE
Create a project template for new blazor project

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#1]
see https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new

**Comment by mingyaulee** [comment]
@newbe36524 that is a great idea to ease first time setup.
I have thought of making the setup easier too, with the first option being creating a project template, which can only be used for new projects.
The second option I can think of, which can also be used for an existing Blazor project, is to add a tool to transform the project (sort of like bootstrapping existing project). The way to activate the tool is to add a build property in the project, something like
`<BlazorBrowserExtensionSetup>true</BlazorBrowserExtensionSetup>` and then build the project.
What's your thought on the second option?

**Comment by newbe36524** [comment]
Before we get to the second project, I think it is more important to discuss whether this feature should be supported or not.
I think the vast majority of developers who are expecting to develop a browser plugin will also have a project that is mostly newly created.
It's hard to imagine a developer expecting to convert on an old project. I think we're missing that use case.

Also as you've considered, the second scenario doesn't require a low cost of development.
So I think it's just a matter of making sure the developer's first initialization goes smoothly.

**Comment by mingyaulee** [comment]
As you have mentioned, a project that is mostly newly created is still an "existing" project, that is what I meant when I was thinking of allowing the developers to convert existing project.
The reason being is that if we start off with the tool that converts a brand new blazor project into a browser extension project, then we can also easily create the project template using this method too.

**Comment by mingyaulee** [comment]
After some consideration I would still go for the second option which is most likely going to be incorporated into the Blazor.BrowserExtension.Build package.

This is because I feel like it would take more effort to keep maintaining the template whenever the blazorwasm template is updated. Also, we can't possibly have support for all the flags that `dotnet new blazorwasm` currently supports if we were to create a template for this project.

**Comment by newbe36524** [comment]
I don`t think we need to keep all options of `dotnet new blazorwasm`, some of them are unavalible ine browser extension.

If you think the second way is easier to maintain, I don't see a problem with that either.
After all, I also lack experience in this part

**Comment by mingyaulee** [comment]
@newbe36524  I have added bootstrapping project steps in the build process and also updated the docs with the easier setup steps with commit 9646aafe7310b663dca467272d4eec37c4b0571b. I do not think I will go with the project template option but you can feel free to work on this. Otherwise, I will proceed to close this issue.

**Comment by newbe36524** [comment]
Great, I will take some action on that in a few weeks.
