### ISSUE TITLE
[Content] 03_01_app.js.md

### ISSUE THREAD

**Issue by edeykholt** [mingyaulee/Blazor.BrowserExtension#108]
On https://mingyaulee.github.io/Blazor.BrowserExtension/app.js, what I found with v1.2.3 and Visual Studio Community was that the name of the file needs to match the namespace in the Program.cs file, and have the form <namespace>.lib.module.d.js.  In addition, it would be helpful if this file was created as a placeholder by default.  It's possible I'm doing something wrong, of course.

**Comment by mingyaulee** [comment]
The `app.js` file can be created in the `wwwroot` directory like in the samples https://github.com/mingyaulee/Blazor.BrowserExtension.Samples/blob/main/SidebarUsingContentScripts/src/wwwroot/app.js

This file is detected during build and loaded automatically by this package instead of Blazor. This package has the module library that you mentioned [here](https://github.com/mingyaulee/Blazor.BrowserExtension/blob/main/src/Blazor.BrowserExtension/content/dist/Blazor.BrowserExtension.lib.module.js) which in turn loads the `app.js` from your project.

**Comment by edeykholt** [comment]
thank you
