### ISSUE TITLE
Are there extensions in the web store that were created using this repo?

### ISSUE THREAD

**Issue by Tony20221** [mingyaulee/Blazor.BrowserExtension#128]
Are there extensions in the web store that were created using this repo? 
Are there working examples of browser extensions on Github that are based on this repo?

**Comment by mingyaulee** [comment]
There are examples of browser extensions in the repository[Blazor.BrowserExtension.Samples](https://github.com/mingyaulee/Blazor.BrowserExtension.Samples).

You can also look at a list of GitHub projects dependent on this package in the [dependents insight page](https://github.com/mingyaulee/Blazor.BrowserExtension/network/dependents).

[EdgeExtensionsBlazor](https://github.com/dragnilar/EdgeExtensionsBlazor) is published on the Edge extension store.

[Amazing-Favorites/Amazing-Favorites](https://github.com/Amazing-Favorites/Amazing-Favorites) is published on the Edge and Chrome extension store.

**Comment by abukres** [comment]
Amazing favorites i using manifest version 2 which is getting deprecated these days. Is there an extension in Chrome Store that uses version 3?

My concern is that Google might not accept extensions developed with Blazor or WebAssembly. I noticed in the extensions files with *.dll.br extension. Are these the actual dll's? I am not sure what the .br extension is about.

Doesn't Google check the regular Javascript based extensions for security holes and malware? I am not sure how they do the same for webassembly files.

**Comment by Tony20221** [comment]
Amazing favorites is using manifest version 2 which is getting deprecated these days. Is there an extension in Chrome Store that uses version 3?

My concern is that Google might not accept extensions developed with Blazor or WebAssembly in manifest 3 as they have more stringent rules with it. I noticed in the extension files with *.dll.br extension. Are these the actual dll's? I am not sure what the .br extension is about.

Doesn't Google check the regular Javascript based extensions for security holes and malware? I am not sure how they do the same for webassembly files.

**Comment by mingyaulee** [comment]
.Net 7 and before compiles to `.dll` whereas .Net 8 compiled to `.wasm` by default, you can look at https://github.com/dotnet/runtime/issues/80807 for this format.

`.br` is the Brotli compression so that the packaged extension is much smaller in size. I suppose the chrome web store will ask for your source code if you attempt to publish an extension using wasm.

Chrome extensions have a [sample project](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/functional-samples/cookbook.wasm-helloworld-print) for showcasing using wasm in extension, which would not make sense if they don't allow extensions built with wasm to be published.
