### ISSUE TITLE
DotNet is undefined in ContentScript / Razor page

### ISSUE THREAD

**Issue by Cle-O** [mingyaulee/Blazor.BrowserExtension#144]
Hello,
I am developing a browser extension with Blazor using your very nice package and template.
I cannot figure out how to call a .Net method from JavaScript. It should work using the "DotNet" object defined as a global variable by Blazor WASM, but the variable remains undefined. So for some reason, Blazor isn't fully working, although I can call JS from a .Net method successfully.

Here is my manifest v3:

```
{
  "manifest_version": 3,
  "name": "PUBROWSE Extension",
  "description": "Hooks into PU market data and suggests good trades.",
  "version": "0.1",
  "background": {
    "scripts": [ "BackgroundWorker.js" ],
    "type": "module"
  },
  "action": {
    "default_popup": "popup.html"
  },
  "options_ui": {
    "page": "options.html",
    "open_in_tab": true
  },
  "permissions": [ "storage", "scripting", "tabs", "debugger", "activeTab" ],
  "host_permissions": [
    "http://*/*",
    "https://*/*"
  ],
  "content_scripts": [
    {
      "matches": [ "*://*/*" ],
      "js": [ "content/Blazor.BrowserExtension/ContentScript.js", "scripts/MainComponent.js", "scripts/Startup.js" ],
      "css": [ "PUBROWSE.styles.css" ]
    }
  ],
  "content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'"
  },
  "web_accessible_resources": [
    {
      "resources": [
        "framework/*",
        "content/*",
        "app.js"
      ],

      "matches": [ "<all_urls>" ]
    }
  ]
}
```

And the ContentScript Startup.js: 

```
console.log("Startup.js called");   
console.log("Is DotNet defined:")
console.log(DotNet)
```

This results in the error "ReferenceError: DotNet is not defined" in FireFox. 
I have also tried it from a Razor component via a button click:

```
 <div>
     <button onclick="console.log(DotNet)">Test</button>
 </div>
```

Also not working. 
Could you please provide me with some insight?

**Comment by mingyaulee** [comment]
I believe the Startup.js is ran before DotNet is defined. As for the button click I think the JavaScript is executed in the page's context instead of the content script context.

You can use `app.js` and call `import()` in the `afterStarted` lifecycle. This way you are guaranteed that Blazor is initialized already when you run the script.

**Comment by Cle-O** [comment]
Thanks for your answer!
I have checked app.js and found out that the _DotNet_ object is available there, so no import() was neccessary.
The question is: why is is not available in other JS files / in my ContentScripts?
What would I have to import exactly to make the Blazor runtime available for JavaScript files?

**Comment by mingyaulee** [comment]
JavaScript libraries are executed immediately when they are loaded, which is before the DotNet library is executed. Basically the other libraries relying on DotNet should be delayed in their execution by importing them after DotNet is available, instead of declared in the manifest as a content script.

**Comment by Cle-O** [comment]
Hmmm, but the button click in the Razor component comes way after initialisation. 
Do you maybe have a working code example where the DotNet object is actually used?

**Comment by mingyaulee** [comment]
The onclick that you have in your Razor code is likely running in the page's context instead of content script context. Instead of using inline onclick, you can either use Blazor's @onclick or attach event handler in JavaScript.

For more information on this, you can read up on the [Work in isolated worlds](https://developer.chrome.com/docs/extensions/develop/concepts/content-scripts#isolated_world) section.

Quoting from the note

> Note: Not only does each extension run in its own isolated world, but content scripts and the web page do too. This means that none of these (web page, content scripts, and any running extensions) can access the context and variables of the others.

**Comment by Cle-O** [comment]
Thank you, that set me on the right track!
The problem was indeed that razor components are isolated from ContentScripts (and background scripts).
So a way to communicate between these party was neccessary, I use `window.postMessage()` to send messages from the ContentScript and receive them with `window.addEventListener(...)`  in the component.

**Comment by mingyaulee** [comment]
The Blazor components actually execute in the Content Scripts context, it's only the inline JavaScript that you inject into the page gets executed in the page's context.

For communications between the different contexts of an extension, you can refer to the newly added [Messaging sample](https://github.com/mingyaulee/Blazor.BrowserExtension.Samples/tree/main/Messaging/src).
