### ISSUE TITLE
How to create a project with sidebar

### ISSUE THREAD

**Issue by wf-soft** [mingyaulee/Blazor.BrowserExtension#17]
![image](https://user-images.githubusercontent.com/62228539/125315093-5dd14880-e369-11eb-8cb8-68d915eb0753.png)

**Comment by wf-soft** [comment]
https://github.com/ovity/octotree/

**Comment by mingyaulee** [comment]
Sidebar is not a standard features across all major browsers. Firefox supports it but not Chrome. A workaround this is to use content scripts to render the sidebar, like octotree you can see that in their extension manifest they are using content scripts to render the sidebar.

https://github.com/ovity/octotree/blob/582c1d6127a6d4b5bce6c9a6b5cf28d31077ae79/src/config/wex/manifest.json#L19-L25

**Comment by wf-soft** [comment]
@mingyaulee Can we make such a content script template for us? I think many people like the plug-ins in the sidebar

**Comment by wf-soft** [comment]
![image](https://user-images.githubusercontent.com/62228539/125379017-57bb8600-e3c2-11eb-9ff2-0647615ee438.png)
![image](https://user-images.githubusercontent.com/62228539/125379040-61dd8480-e3c2-11eb-941b-3452f3d1ac7d.png)

**Comment by wf-soft** [comment]
![image](https://user-images.githubusercontent.com/62228539/125379078-74f05480-e3c2-11eb-80db-4567e6f09f02.png)
![image](https://user-images.githubusercontent.com/62228539/125379104-846f9d80-e3c2-11eb-9709-5b89cce6623d.png)

**Comment by mingyaulee** [comment]
@wf-soft it is certainly possible but I would consider it to be out of scope for this project because everyone can implement something different with content scripts, for example using different CSS frameworks (Bulma, Bootstrap, ...) and having different layout (width, height, fixed/scroll with page etc.). It has pretty much endless combinations of implementation strategy. In my opinion, this will fit for creation of another repository to showcase what kind of features can be implemented inside an extension.

**Comment by mingyaulee** [comment]
I have added a couple samples in a separate [template repository](https://github.com/mingyaulee/Blazor.BrowserExtension.Samples)

More are coming soon!

**Comment by wf-soft** [comment]
@mingyaulee Fantastic！
