### ISSUE TITLE
how to debug

### ISSUE THREAD

**Issue by yuzd** [mingyaulee/Blazor.BrowserExtension#29]
Have you tested the debug can work？
![image](https://user-images.githubusercontent.com/16083659/133917167-0cb1a0f4-3f59-41c7-b535-5a69488434b1.png)

i tested was not working!

**Comment by mingyaulee** [comment]
The debug for web assembly as of now should work if you are debugging from the IDE. However, doing so means you will not get the extensions API and you will have to mock the response for the APIs used by the project. This is because the debugging feature in Blazor uses NodeJS as a debugging proxy and when running the project as a browser extension, this proxy is not running. AFAIK, we can't debug a published Blazor app until the team releases a browser extension that would enable debugging from just the DevTools, something like the React Developer Tools for debugging React apps.

**Comment by yuzd** [comment]
That means that the chrome extentions developed by blazor cannot debug c# code, right?

**Comment by mingyaulee** [comment]
That is right, it is only possible to debug it from the IDE for now. When it is loaded in the browser as an extension, it will be possible to debug once there is official support for it, either from Blazor or Chrome DevTools, or both.
