### ISSUE TITLE
[Bug] Build with <BrowserExtensionBootstrap>true</BrowserExtensionBootstrap> reset files

### ISSUE THREAD

**Issue by pawelel** [mingyaulee/Blazor.BrowserExtension#32]
![Animation](https://user-images.githubusercontent.com/14290787/139532833-5673b184-3157-45c5-8ca6-24988a78117a.gif)
Without `<BrowserExtensionBootstrap>true</BrowserExtensionBootstrap>`:
![Animation](https://user-images.githubusercontent.com/14290787/139532902-a99e8023-7aee-43c8-a55b-0ebfe76f0542.gif)

**Comment by mingyaulee** [comment]
That is quite the intention really, is there a reason that you need to bootstrap the project more than once?

**Comment by pawelel** [comment]
> That is quite the intention really, is there a reason that you need to bootstrap the project more than once?

I don't understand. Is the bootstrap bundled? I'm trying to go with the manual and didn't find any reference to bootstrap except the lines about default disabled and how to add manually. In perfect scenario I'd use MudBlazor library instead, but don't know if it is possible and if so - how.

**Comment by mingyaulee** [comment]
The build property `BrowserExtensionBootstrap` here is a feature that allows developers to bootstrap (setup) their existing Blazor wasm project into a browser extension project, which is one time use only. This is not related to the bootstrap CSS framework which is not included in this package.

By design, this package should be compatible with all the component/CSS frameworks. So the usage of the frameworks will just be to follow their official documentation.

**Comment by pawelel** [comment]
Thank you for explanation.
