### ISSUE TITLE
ShadowDom

### ISSUE THREAD

**Issue by ProIcons** [mingyaulee/Blazor.BrowserExtension#38]
in content scripts some times you would want to have isolated stylesheets, so page's css won't affect your own content script's html. At this point is worth noting that i just read about shadow dom in here: https://stackoverflow.com/a/20241247 and i'm not sure how it works. But will this library support it in any way?

**Comment by mingyaulee** [comment]
Blazor supports CSS isolation out of the box. You can read on the documentation [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0). The good thing with Blazor is you do not need to really know about the DOM for simple use cases, because Blazor controls the creation and removal of the DOM elements.
