### ISSUE TITLE
how to get current active tab via WebExtensions.Net.Tabs.Tab ?

### ISSUE THREAD

**Issue by hanxiao123** [mingyaulee/Blazor.BrowserExtension#63]
In Popup.razor,
` IEnumerable<WebExtensions.Net.Tabs.Tab> tabs = new List<WebExtensions.Net.Tabs.Tab>();`
the tabs.Count() is 0.
I need to get current active tab and inject jquery.js to interop dom.is there possible to achieve it ?

**Comment by mingyaulee** [comment]
A quick search on the extension API landed me on https://stackoverflow.com/questions/17076408/chrome-extension-what-is-the-active-tab-in-2-opened-windows/17076501#17076501

Since we are using the web extensions polyfill, the callback is wrapped into an asynchronous function. So from the popup you can just call to the same API without the callback parameter.
