### ISSUE TITLE
Add support for non-async APIs like chrome.i18n?

### ISSUE THREAD

**Issue by datvm** [mingyaulee/Blazor.BrowserExtension#66]
Right now all APIs are asynchronous because under the hood, `IJSRuntime` is being used. This is very bad when we need APIs call from `.razor` pages (which do not support async) and every `chrome.i18n.getMessage` call is asynchronous which is not very fast IMO and there is no way to batch call this as far as I am aware of.

Can we add suport for `IJSInProcessRuntime`? I am happy to do a PR for this.

**Comment by mingyaulee** [comment]
Sorry for the late reply. The APIs are mostly asynchronous and if you look at the implementation in Chrome, they have a callback parameter, which is being converted to asynchronous promise-based APIs by the polyfill.
The APIs that are not asynchronous are not many, but it is exactly the same as of now with `IJSRuntime` and `IJSInProcessRuntime` due to being single threaded in the browser.
