### ISSUE TITLE
Blazor.BrowserExtension.Template could not be installed, the package does not exist.

### ISSUE THREAD

**Issue by JoaquinSuez** [mingyaulee/Blazor.BrowserExtension#78]
```
C:\WINDOWS\syastem32>dotnet new --install Blazor.BrowserExtension.Template
Warning: use of 'dotnet new --install' is deprecated. Use 'dotnet new install' instead.
For more information, run:
   dotnet new install -h

The following template packages will be installed:
   Blazor.BrowserExtension.Template

Blazor.BrowserExtension.Template could not be installed, the package does not exist.

For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
```

I'm getting this error, I'm pretty new to this so I don't know if there is any other way to install the package.

**Comment by mingyaulee** [comment]
For a start, you can try to see if you can find the template NuGet package in any of your existing projects package manager. It could be due to network restriction, maybe corporate network that requires setting up proxy to access NuGet.org.

To see more details when installing the template you can use `dotnet new install Blazor.BrowserExtension.Template -v normal` to check what happened or even `-v diagnostic` if you want to see all the logs.

**Comment by mingyaulee** [comment]
Closed due to inactivity. Please reopen if the issue still persist.
