### ISSUE TITLE
Rejection from Chrome Web Store

### ISSUE THREAD

**Issue by mattgwagner** [mingyaulee/Blazor.BrowserExtension#79]
Thank you for your hard work! We've been using Blazor Web Assembly on our extension for several years. We went to push an update this week and it got rejected by the Chrome Web Store. I submitted a ticket with them to get more information, but I'm getting the feeling it's because of the opaque nature of the WASM. It's even weirder since I submitted and was approved on our other, unlisted version that we use for beta testing, within the past 7 days.

Any thoughts on this?

![Chrome Web Store Rejection notification for Esferas io - Gmail 2023-10-26 at 8 58 36 AM](https://github.com/mingyaulee/Blazor.BrowserExtension/assets/157644/2f0ae211-fdde-450f-960f-228c05855664)

**Comment by mingyaulee** [comment]
To be honest I have no idea of what could be the reason for the rejection, since the official chrome documentation says that you can allow wasm code to run by using the wasm-unsafe-eval in the CSP https://developer.chrome.com/docs/extensions/migrating/improve-security/#remove-unsupported-csv

**Comment by mattgwagner** [comment]
You know, that's what I thought, too, and that's what I've been working under the assumption of for the past 11 months since migrating to manifest v3. I wasn't sure if you had seen anything else for devs using the package.

I thought it might be my addition of using SignalR, but they approve the unlisted 'beta' version but not the user-facing listing.

I'll let you know if my support ticket/appeal identifies anything specifically.

Thanks!!

**Comment by mingyaulee** [comment]
Hmm, that could be something worth looking into. I'm assuming you are using the signalr client npm package instead of nuget package because I'm guessing the use is in the service worker JS. 

Either way, one thing you can check on is if any file included in the packed extension package contains reference to another script file from the CDN/other source.

One of such library is the firebase JS SDK with an open issue https://github.com/firebase/firebase-js-sdk/issues/7617

If there's nothing then the only way is to wait for the support team to investigate and pinpoint where exactly the violation happens.

PS: Thanks for the contribution, it means a lot to me!

**Comment by mattgwagner** [comment]
In this case, I'm using `Microsoft.AspNetCore.SignalR.Client` from Blazor Web Assembly by having my extension pop a full page that the users leave running... the intent with SignalR was to have a heartbeat and keep the WebSocket connection open, in the hopes that Chrome would stop putting the page to sleep.

I'm going to do a comparison between a previous, approved built extension and the one submitted to see if there's something that they flagged during review... it was just particularly odd since they approved the same build a few days before!

**Comment by mingyaulee** [comment]
Ah okay. Perhaps you have tried it before, but instead of signalr, maybe you can use the [runtime.connect()](https://developer.chrome.com/docs/extensions/reference/runtime/#method-connect) API to maintain a heartbeat connection to the service worker, thus keeping the page alive.

It is weird that they approved the same build for beta but not for public. I am interested to find out what the support team responds. Hope to hear from you how it can be resolved.

**Comment by mattgwagner** [comment]
Turns out, in the Radzen Blazor component library that I've been using for 18-24 months has a single place where you could, potentially, pull in the Google Maps JS library to use that component. Gah! Of all of the things for them to take issue with!

**Comment by mingyaulee** [comment]
Aha okay, that is surprising given how long you have been using it. One of those "fun" surprises you get every now and then from software development.
